/*
* generated by Xtext
*/
package php.ware.ui.contentassist;

import php.ware.ui.contentassist.AbstractWebProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class WebProposalProvider extends AbstractWebProposalProvider {

}
