/*
* generated by Xtext
*/
package php.ware.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class WebTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
